import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lampoon.xyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="site-logo">
          <a href="/" aria-label="Lampoon Home">
            <img src="/41jz38hqDRL.png" alt="Lampoon logo" />
          </a>
        </header>
        {children}
      </body>
    </html>
  );
}
